project:
  type: website
  output-dir: docs
  preview:
    port: 3333
  resources: 
    - "portfolio/1_TOD_Boston/index.qmd"
    - "portfolio/2_DevTracker/index.qmd"
    - "portfolio/3_MappingChallenge/index.qmd"
    - "portfolio/4_SF_Park/index.qmd"
    - "portfolio/5_Flood/index.qmd"
    - "portfolio/6_FightKit/index.qmd"

website:
  title: "Samriddhi Khare"
  site-url: "https://samriddhikhar3.github.io/"
  repo-url: "samriddhikhar3.github.io"
  repo-actions: [source]
  description: "Urban Planner and Spatial Analyst"
  page-navigation: true
  back-to-top-navigation: false
  twitter-card: true
  search: 
    location: navbar
    type: overlay
  comments: 
    utterances: 
      repo: samriddhikhar3/samriddhikhar3.github.io
      label: utterances
      theme: body-light
      issue-term: title
 
  navbar:
    tools:
    - icon: github
      href: https://github.com/samriddhikhar3
    - icon: linkedin
      href: https://www.linkedin.com/in/samriddhi-khare-3668821b1/
    right:
      - text: Home
        aria-label: "Resume"
        href: index.qmd
      - text: Resume
        aria-label: "Resume"
        href: resume.qmd
      - text: Portfolio
        aria-label: "Portfolio"
        href: portfolio/portfolio.qmd
  
  page-footer:  
    center: >-
     Made with ❤️ and [Quarto](https://quarto.org)

format: 
  html: 
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5rem
    link-external-newwindow: true
    theme: cosmo
      #light: cosmo         #FOR SOME REASON CAUSING ERRORS. FIX LATER
      #dark: [cosmo, theme-dark.scss]
    highlight-style: solarized
    code-link: true
    code-copy: true
    toc: true
    pagetitle: "{{< meta title >}} | Samriddhi Khare"

execute: 
  freeze: auto
  cache: true

