---
title: "Samriddhi Khare"
subtitle: "Data Analyst and Urban Planner"
about:
  id: hero-heading
  image-width: 0em
  template: solana
  links:
    - icon: journal-code
      text: PDF
      href: https://github.com/samriddhikhar3/samriddhikhar3.github.io/blob/main/images/SK_Resume.pdf
---


## Experience

#### <b>Econsult Solutions</b>  *Philadelphia, PA*
###### Data Analyst (June 2023 – Present)
* Led the development of machine learning models in Python and R to estimate economic and fiscal impacts of transit projects, housing, and urban green infrastructure supporting over 30 local and nationwide agencies.
* Designed static and interactive geospatial data visualizations and dashboards using ArcGIS, QGIS, R, Python and Power BI; Drove firm-wide integration of Adobe Creative Suite to elevate creative production.
* Conducted economic and fiscal impact studies for institutional, housing, and transit projects using R, Excel, and IMPLAN for public and private sector clients.
* Authored memos and reports for heads of city, state and transit agencies to inform regional and institutional policy.

#### <b>PennPraxis</b>  *Philadelphia, PA*
###### Research Assistant Intern (February 2023 – Present)
* Calculated a school closure vulnerability index to inform the School District of Philadelphia’s facilities planning process using R and ArcGIS
* Created statistical models to preemptively mitigate the student redistribution at schools at risk for closure

#### <b>Studio Sakha Ajni</b>  *Nagpur, India*
###### GIS Consultant (October 2021 – January 2022)
* Prepared a site plan for airport construction using Landsat raster classification, predictive spatial analysis in Google Earth Engine, and remote sensing workflows in Python. 
* Mobilized groups of over 200 volunteers and professionals to prevent the destruction of 500+ acres of green buffer. 

#### <b>City for All: Alliance Française and Social Design Collaborative</b>  *New Delhi, India*
###### Program Facilitator (May 2022 – June 2022)
* Facilitated trans-national focus group discussions between French and Indian city planners and lower-income queer communities in New Delhi.
* Mapped different marginalized groups’ access to public spaces across multiple cities in India and France to be published as open source data.

## Education

#### <b>University of Pennsylvania</b>  *Philadelphia, PA*
###### Master of City Planning; Concentration in Urban Technology and Spatial Analytics 
* Coursework: Urban Spatial Analysis, GIS, Quantitative Planning Methods, Land Use and Environmental Modeling, Geospatial Analysis in Python, Public Policy Analytics, Communication in Urban Spatial Analytics, Geospatial Cloud Computing, Machine Learning in Remote Sensing, Planning Workshop
* Honors/Awards: Dean’s Merit Scholarship ($50,000) 

#### <b>Visvesvarya National Institute of Technology</b>  *Nagpur, India*
###### Bachelor of Architecture 
* Honors/Awards: Graduated 95th Percentile. Awarded distinction in Architecture Design, Landscape Design, Urban Planning and Design, and Climatology
* Elected Batch Representative, 2017; Elected English Literary Secretary, Collegiate Magazine, 2020

## Projects and Certifications

#### <b>TOD Planning and Benefit Cost Analyses</b>  *NJ Transit*
###### (Nov 2024 – Feb 2026)
* Led the modeling of ridership/revenue and train delays to optimize transit service planning and revenue performance. 
* Developed a comparative tool to model financial metrics (ROI, IRR, NOI) for future capital projects and operational scenarios.  
* Supported federal and state grant applications by conducting benefit–cost analyses for fleet electrification, rail yard improvements, bridge replacements, and track expansion projects.
* Designed maps and data visualizations integrating transit routes, land use, and demographic data to support transit-oriented development (TOD) and capital planning.

#### <b>[Return on Investment in the Environment](https://www.norcopa.gov/index.php?section=press-releases&prrid=199)</b>  *Northampton County, PA*
###### (Dec 2024 – Aug 2025)
* Developed machine learning models in R and Python to quantify the impact of parks and open space on property values.
* Engineered features from Census and assessment datasets and classified using a logistic regression 
* Calculated the economic impacts of agriculture and natural system services, including carbon sequestration, public health benefits, and outdoor recreation economics

#### <b>[Interactive Housing Analysis Dashboard](https://www.nheconomy.com/office-of-planning-and-development/fiscal-housing-calculator)</b>  *State of New Hampshire*
###### (Aug 2024 – June 2025)
* Created an interactive Power BI dashboard to model assessed value of new construction, municipal expenditures, and impacts on the local tax base.
* Developed a classification matrix for 145 municipalities across varying housing densities using k-means clustering in Python. 
* Conducted regression analyses to quantify the marginal impact of increased housing density on municipal costs

#### <b>Geographic Information Services Professional Certificate</b>  *GIS Vision, India*
###### (Nov 2024 – Feb 2026)
* Completed professional certification in GIS services such as ArcGIS Pro, 3D, QGIS, Network Analysis, Digital Elevation Models, Predictive Flood Modelling, and Raster Analysis

## Fellowships and Awards

#### <b>[Center for the Living City, OAN Fellow](https://centerforthelivingcity.org/oan-fellows-2021#oanfellows2021-pehchaan:~:text=TEAM%20MEMBERS-,Samriddhi%20Khare,-Pranita%20Varma)</b> *Scranton, PA + New Delhi/Nagpur/Bangalore, India*
* Established an Indian think tank for interdisciplinary urban research
* Designed labels for public space/transport, and toolkits for mobility mapping of sexual minorities 
* Spearheaded the construction and curation of a travelling, modular public art exhibition featuring minority artists 


#### <b>[15 Minute City Competition, Honorary Mention](https://thecharette.org/15-minute-city-2022-results/#:~:text=Honourable%20Mention-,Samriddhi%20Khare,-%E2%80%A2%C2%A0%20Pranita%20Varma%C2%A0%20%E2%80%A2%C2%A0%20Raunak)</b> *The Charette, International Competition*           
* Developing a context driven solution to urban issues in Nagpur, India focusing on planning amenities within a 15 minute walkability radius  

#### <b>[Berkeley Essay Prize, Fourth Place](https://berkeleyprize.org/competition/essay/2022/winning-essays/samriddhi-khare-and-jiya-anand-essay)</b> *University of California, Berkeley*
* Essay titled “New Delhi and the Planning of Carcerality” examining inadequacies in affordable housing in relation to recidivism and incarceration in New Delhi, with the help of geo-statistical analyses   

#### <b>SURF 2020 Conference, Research Author</b> *Bearys Institute of Technology, Mangalore, India*                                   
* Publication titled “Chitar Oli and the Analysis of Caste” studying the developmental manifestation of caste-based income inequality and residential segregation 


## Skills and Interests

* <b>Technical:</b>  R, Python, SQL, JavaScript, ArcGIS (Pro and Online), QGIS, VISUM/VISSIM, Google Earth Engine, MS Suite, Adobe Creative Suite, CAD, Rhino + Grasshopper
* <b>Skills:</b> Spatial & Statistical Analysis, GIS, Machine Learning, Data Visualization and Storytelling, Policy-Oriented Technical Writing
* <b>Professional Interests:</b> Digital Equity, Fair Algorithms, Transportation Planning, Climate Tech, Climate Change Mitigation/Adaptation, Urban Data, Smart Cities

#### [See my portfolio &rarr;](/portfolio/portfolio.html)