title: "samriddhi khare: data and design portfolio" # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  hi! i'm sam. (she/her)
  <br><br>
  i'm fascinated by the world of maps and data. this portfolio is a collection of my projects. as someone who finds joy in uncovering insights within data, i'm excited to share my journey with you.   
  <br><br>
  <a href="https://www.linkedin.com/in/samriddhi-khare-3668821b1/">View My LinkedIn Profile</a> 
  
remote_theme: riggraz/no-style-please
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
