project:
  type: website
  output-dir: docs
  preview:
    port: 3333
  resources: 
    - "portfolio/3_Zillow/Zillow.html"
    - "portfolio/2_ON_TRACK/ON_TRACK.html"

website:
  title: "Samriddhi Khare"
  site-url: "https://samriddhikhar3.github.io/"
  repo-url: "https://github.com/samriddhikhar3/samriddhikhar3.github.io"
  repo-actions: [source]
  description: "Urban Planner and Spatial Analyst"
  favicon: images/cell_towers.png
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  search: 
    location: navbar
    type: overlay
  comments: 
    utterances: 
      repo: samriddhikhar3/samriddhikhar3.github.io
      label: utterances
      theme: body-light
      issue-term: title
 
  navbar:
    logo: images/cell_towers.png
    tools:
    - icon: github
      href: https://github.com/samriddhikhar3
    - icon: linkedin
      href: https://www.linkedin.com/in/samriddhi-khare-3668821b1/
    right:
      - text: About
        aria-label: "About"
        href: about.qmd
      - text: Resume
        aria-label: "Resume"
        href: resume.qmd
      - text: Portfolio
        aria-label: "Portfolio"
        href: portfolio/portfolio.qmd
  
  page-footer:  
    center: >-
     &#169; 2024 Stephanie Cheng &#8729; Made with ❤️ and [Quarto](https://quarto.org)

format: 
  html: 
    grid:
      sidebar-width: 250px
      body-width: 800px
      margin-width: 250px
      gutter-width: 1.5rem
    link-external-newwindow: true
    theme: cosmo
      #light: cosmo         #FOR SOME REASON CAUSING ERRORS. FIX LATER
      #dark: [cosmo, theme-dark.scss]
    highlight-style: solarized
    code-link: true
    code-copy: true
    toc: true
    pagetitle: "{{< meta title >}} | Stephanie Cheng"

execute: 
  freeze: auto
  cache: true

