---
title: "Samriddhi Khare"
subtitle: "Urban Planner and Spatial Analyst"
---

## Education

#### <b>University of Pennsylvania</b>  *Philadelphia, PA*
###### Master of City Planning; Concentration in Urban Technology and Spatial Analytics 
* Relevant coursework: Quantitative Planning Methods, Land Use and Environmental Modeling, Geospatial Analysis in Python, Public Policy Analytics, Communication in Urban Spatial Analytics, Geospatial Cloud Computing, Machine Learning in Remote Sensing, Planning Workshop
* Honors/Awards: Dean’s Merit Scholarship ($50,000) 

#### <b>Visvesvarya National Institute of Technology</b>  *Nagpur, India*
###### Bachelor of Architecture 
* Honors/Awards: Graduated 95th Percentile. Awarded distinction in Architecture Design, Landscape Design, Urban Planning and Design, and Climatology
* Elected Batch Representative, 2017; Elected English Literary Secretary, Collegiate Magazine, 2020

## Professional Experience

#### <b>Econsult Solutions: Center for the Future of Cities</b>  *Philadelphia, PA*
###### Research and Analysis Intern (June 2023 – Present)
* Developed a climate resilience index for major US Cities using qualitative and quantitative research, tested the data using sensitivity training minimizing errors and 
* Wrote multiple articles on urban planning and data using data privacy 

#### <b>PennPraxis</b>  *Philadelphia, PA*
###### Analysis and Design Intern (February 2023 – Present)
* Developed a vulnerability to closure index for Philadelphia’s school for local government and school districts to inform their facilities planning process
* Created statistical models to preemptively mitigate the student redistribution at schools at risk for closure 
* Coordinated stakeholder meetings for activists and public school stakeholders

#### <b>Netter Center for Community Partnerships</b>  *Philadelphia, PA*
###### Programming Intern (August 2022 – December 2022)
* Worked with a network of Philadelphia High Schools to develop curricula and mentor students for personal and professional development 
* Conducted research to support the production of materials for partner schools and students for grant applications, and research/policy briefs

#### <b>City for All: Alliance Française and Social Design Collaborative</b>  *New Delhi, India*
###### Program Facilitator (May 2022 – June 2022)
* Facilitated trans-national focus group discussions between French and Indian city planners and lower-income queer communities in New Delhi
* Mapped different marginalized groups’ access to public spaces across multiple cities in India and France to be published as open source data 

#### <b>Saving Ajni</b>  *Nagpur, India*
###### GIS Consultant (October 2021 – January 2022)
* Mobilized groups of over 200 volunteers and professionals to prevent the felling of 500+ acres of green buffer 
* Worked on alternate site proposal using GIS analyses (NDVI and LST comparisons and projections), managed press, petitions and campaigns 


## Fellowships and Awards

#### <b>[Center for the Living City, OAN Fellow](https://centerforthelivingcity.org/oan-fellows-2021#oanfellows2021-pehchaan:~:text=TEAM%20MEMBERS-,Samriddhi%20Khare,-Pranita%20Varma)</b> *Scranton, PA + New Delhi/Nagpur/Bangalore, India*
* Established an Indian think tank for interdisciplinary, LGBTQ+ focused urban research
* Designed labels for LGBT-affirming public space/transport, and toolkits for mobility mapping of sexual minorities 
* Spearheaded the construction and curation of a travelling, modular public art exhibition featuring queer artists 
* Organized sexual orientation and gender identity sensitization workshops for architects and planners 

#### <b>[15 Minute City Competition, Honorary Mention](Samriddhi Khare)</b> *The Charette, International Competition*           
* Developing a context driven solution to urban issues in Nagpur, India focusing on planning amenities within a 15 minute walkability radius  

#### <b>[Berkeley Essay Prize, Fourth Place](https://berkeleyprize.org/competition/essay/2022/winning-essays/samriddhi-khare-and-jiya-anand-essay)</b> *University of California, Berkeley*
* Essay titled “New Delhi and the Planning of Carcerality” examining inadequacies in affordable housing in relation to recidivism and incarceration in New Delhi, with the help of geo-statistical analyses   

#### <b>Public Policy Forum, Merit Scholar</b> *GovLab, New York University*                                                     
* 1 of 3 scholars in a cohort of 40 engaged in policy simulations related to participatory budgeting, public policy and equity

#### <b>SURF 2020 Conference, Presenter</b> *Bearys Institute of Technology, Mangalore, India*                                   
* Publication titled “Chitar Oli and the Analysis of Caste” studying the developmental manifestation of caste-based income inequality and residential segregation 


## Skills and Interests

* <b>Data Analysis/Programming Skills:</b> R, Python, SQL, C/C++, ESRI ArcGIS Pro/Online, Excel, HTML, CSS
* <b>Media Skills:</b> Adobe Photoshop/Illustrator/InDesign
* <b>Professional Interests:</b> Digital Equity, Fair Algorithms, Transportation Planning, Climate Tech, Renewable Energy, Climate Change Mitigation/Adaptation, Urban Data, Smart Cities, Urban Sensors

#### [See my portfolio &rarr;](/portfolio/portfolio.html)